config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'movies#index'

  resources :movies, only: [:destroy, :show, :index] do
    resources :bookmarks, only: [:index, :new, :create]
  end
  resources :bookmarks, only: [:destroy]
  resources :lists, only: [:new, :create, :index, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, presence: true, uniqueness: { scope: :list }
  validates :list, presence: true, uniqueness: { scope: :movie }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    # raise
    @bookmark = Bookmark.new
    # where the Fs my movie?
    @movie = Movie.find(params[:movie_id])
  end

  def create
  end

  def destroy
    Bookmark.destroy
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @list = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    # got ma params
    # wanna create inst with info from params
    # save instance (persist to db)
    @list = List.create(strong_params)
    if @list.valid?
      redirect_to movies_path
    else
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to movies_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def strong_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
    @lists = List.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def destroy
    @movie.destroy
    redirect_to movies_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Create a New Bookmark</h1>
<%= simple_form_for [@movie, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :list, as: :radio_buttons %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <i class="fas fa-sad-tear"></i>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="/movies">This</a>
            <a class="nav-link" href="/lists">Idea</a>
            <a class="nav-link" href="<%= new_list_path %>">Is</a>
            <a class="nav-link disabled">Dumb</a>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/_list.html.erb
<div class="col-6">
  <div class="card my-3">
  
    <%= link_to list_path(list) do %>
      <div class="card-category text-center" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
        <%= list.name %>
      </div>
    <% end %>

    <%= link_to "🗑", list_path(list), method: :delete %>
  </div>
</div>

app/views/lists/create.html.erb
<h1>Build  List</h1>

app/views/lists/index.html.erb
<%# nothing here %>

app/views/lists/new.html.erb
<h1>Build a new List</h1>
<p>Find me in app/views/lists/new.html.erb</p>

<div class="form">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/random/?<%= @list.name %>);">
  <div class="container text-center">
    <h1><%= @list.name %></h1>
    <%# list all bookmarks of movies tagged to this list? %>
  </div>
</div>

app/views/movies/_movie.html.erb
<div class="col-4">
  <%= link_to movie_path(movie) do %>
    <div class="card my-3">
      <img class="img-thumbnail" src="<%= movie.poster_url %>" alt="movie poster image">
      <div class="card-body">
        <h4><%= movie.title %></h4>
        <p><%= movie.overview %></p>
        <%= link_to new_movie_bookmark_path(movie) do %>
          <i class="far fa-bookmark"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/destroy.html.erb
<h1>Movies#destroy</h1>
<p>Find me in app/views/movies/destroy.html.erb</p>

app/views/movies/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/random/movie);">
  <div class="container text-center">
    <h1>Movies</h1>
    <p>help pls</p>
    <%= link_to 'Create new list', new_list_path %>

  </div>
</div>

<div class="container">
  <div class="row">
    <%= render @movies %>
  </div>
  <h2">Movie Lists</h2>
  <div class="row">
    <%= render @lists %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="container">
  <h1><%= @movie.title %></h1>
  <img class="img-thumbnail" src="<%= @movie.poster_url %>" alt="movie poster image">
  <p class="text-center"><%= @movie.overview %></p>
</div>